### ISSUE TITLE
App crashing after completing a game

### ISSUE THREAD

**Issue by sultanahamer** [SecUSo/privacy-friendly-solitaire#19]
Here is a logcat capture﻿

```
2020-02-12 21:03:12.057 17727-17727/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.secuso.privacyfriendlysolitaire, PID: 17727
    java.lang.IllegalStateException: Fragment org.secuso.privacyfriendlysolitaire.Activities.Solitaire.WonDialog must be a public static class to be  properly recreated from instance state.
        at android.app.BackStackRecord.doAddOp(BackStackRecord.java:429)
        at android.app.BackStackRecord.add(BackStackRecord.java:409)
        at android.app.DialogFragment.show(DialogFragment.java:229)
        at org.secuso.privacyfriendlysolitaire.Activities.Solitaire.alertBoxWonMessage(Solitaire.java:334)
        at org.secuso.privacyfriendlysolitaire.Activities.Solitaire$7.run(Solitaire.java:486)
        at android.os.Handler.handleCallback(Handler.java:869)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:6784)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)
```

**Comment by sleep-yearning** [comment]
Hello @sultanahamer, thank you for reporting the bug. Does this happen everytime or just sometimes/once?

**Comment by sultanahamer** [comment]
@sleep-yearning this is happening after every single game completion.
